# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<EOSCRIPT

read -d '' PUBLIC_KEY <<EOF
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2

mQENBFOpvpgBCADkP656H41i8fpplEEB8IeLhugyC2rTEwwSclb8tQNYtUiGdna9
m38kb0OS2DDrEdtdQb2hWCnswxaAkUunb2qq18vd3dBvlnI+C4/xu5ksZZkRj+fW
tArNR18V+2jkwcG26m8AxIrT+m4M6/bgnSfHTBtT5adNfVcTHqiT1JtCbQcXmwVw
WbqS6v/LhcsBE//SHne4uBCK/GHxZHhQ5jz5h+3vWeV4gvxS3Xu6v1IlIpLDwUts
kT1DumfynYnnZmWTGc6SYyIFXTPJLtnoWDb9OBdWgZxXfHEcBsKGha+bXO+m2tHA
gNneN9i5f8oNxo5njrL8jkCckOpNpng18BKXABEBAAG0MlNhbHRTdGFjayBQYWNr
YWdpbmcgVGVhbSA8cGFja2FnaW5nQHNhbHRzdGFjay5jb20+iQE4BBMBAgAiBQJT
qb6YAhsDBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRAOCKFJ3le/vhkqB/0Q
WzELZf4d87WApzolLG+zpsJKtt/ueXL1W1KA7JILhXB1uyvVORt8uA9FjmE083o1
yE66wCya7V8hjNn2lkLXboOUd1UTErlRg1GYbIt++VPscTxHxwpjDGxDB1/fiX2o
nK5SEpuj4IeIPJVE/uLNAwZyfX8DArLVJ5h8lknwiHlQLGlnOu9ulEAejwAKt9CU
4oYTszYM4xrbtjB/fR+mPnYh2fBoQO4d/NQiejIEyd9IEEMd/03AJQBuMux62tjA
/NwvQ9eqNgLw9NisFNHRWtP4jhAOsshv1WW+zPzu3ozoO+lLHixUIz7fqRk38q8Q
9oNR31KvrkSNrFbA3D89uQENBFOpvpgBCADJ79iH10AfAfpTBEQwa6vzUI3Eltqb
9aZ0xbZV8V/8pnuU7rqM7Z+nJgldibFk4gFG2bHCG1C5aEH/FmcOMvTKDhJSFQUx
uhgxttMArXm2c22OSy1hpsnVG68G32Nag/QFEJ++3hNnbyGZpHnPiYgej3FrerQJ
zv456wIsxRDMvJ1NZQB3twoCqwapC6FJE2hukSdWB5yCYpWlZJXBKzlYz/gwD/Fr
GL578WrLhKw3UvnJmlpqQaDKwmV2s7MsoZogC6wkHE92kGPG2GmoRD3ALjmCvN1E
PsIsQGnwpcXsRpYVCoW7e2nW4wUf7IkFZ94yOCmUq6WreWI4NggRcFC5ABEBAAGJ
AR8EGAECAAkFAlOpvpgCGwwACgkQDgihSd5Xv74/NggA08kEdBkiWWwJZUZEy7cK
WWcgjnRuOHd4rPeT+vQbOWGu6x4bxuVf9aTiYkf7ZjVF2lPn97EXOEGFWPZeZbH4
vdRFH9jMtP+rrLt6+3c9j0M8SIJYwBL1+CNpEC/BuHj/Ra/cmnG5ZNhYebm76h5f
T9iPW9fFww36FzFka4VPlvA4oB7ebBtquFg3sdQNU/MmTVV4jPFWXxh4oRDDR+8N
1bcPnbB11b5ary99F/mqr7RgQ+YFF0uKRE3SKa7a+6cIuHEZ7Za+zhPaQlzAOZlx
fuBmScum8uQTrEF5+Um5zkwC7EXTdH1co/+/V/fpOtxIg4XO4kcugZefVm5ERfVS
MA==
=dtMN
-----END PGP PUBLIC KEY BLOCK-----
EOF

{% if cookiecutter.vagrant_box == 'debian8' -%}

APT_REPO_FILE="/etc/apt/sources.list.d/saltstack.list"
APT_REPO="deb http://repo.saltstack.com/apt/debian/8/amd64/latest jessie main"

# Add the saltstack repostory
# TODO: Check if repository exists
echo "$APT_REPO" > $APT_REPO_FILE

# Trust the saltstack repository signing key
echo "$PUBLIC_KEY" | apt-key add -

# Install salt minion and python testing tools
apt-get update
apt-get install -y salt-minion python-pip

{%- elif cookiecutter.vagrant_box == 'centos7' -%}

YUM_REPO_FILE="/etc/yum.repos.d/saltstack.repo"
YUM_REPO_KEY_FILE="/etc/pki/rpm-gpg/SALTSTACK-GPG-KEY.pub"

cat <<EOF > $YUM_REPO_FILE
[saltstack]
name=SaltStack repo for RHEL/CentOS \\\$releasever
baseurl=http://repo.saltstack.com/yum/redhat/\\\$releasever/\\\$basearch/latest
enabled=1
gpgcheck=1
gpgkey=file://$YUM_REPO_KEY_FILE
EOF

echo "$PUBLIC_KEY" > $YUM_REPO_KEY_FILE

# Trust the saltstack repository signing key
rpm --import $YUM_REPO_KEY_FILE

# Install salt minion
yum install -y salt-minion

# Instal EPEL Repository
echo "Installing EPEL repository..."
EPEL_REPO='http://fedora.uberglobalmirror.com/epel/\$releasever/\$basearch'
EPEL_REPO_FILE="/etc/yum.repos.d/epel.repo"

# python-pip is in the EPEL repositories
yum install -y epel-release

# configure epel to use a specific mirror
echo sed -i "s/^\\(mirrorlist=\\)/#\\1/g" $EPEL_REPO_FILE
sed -i "s/^\\(mirrorlist=\\)/#\\1/g" $EPEL_REPO_FILE
echo sed -i "s|^#\\(baseurl=\\).*$|\\1$EPEL_REPO|g" $EPEL_REPO_FILE
sed -i "s|^#\\(baseurl=\\).*$|\\1$EPEL_REPO|g" $EPEL_REPO_FILE

# Install pip
yum install -y python-pip

{%- endif %}

pip install testinfra

# Configure Minion
cat <<EOF > /etc/salt/minion
file_client: local

file_roots:
  base:
    - /srv/salt
    - /srv/salt/tests/states

pillar_roots:
  base:
    - /srv/salt/tests/pillar
EOF

EOSCRIPT

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

{% set vm_box = {
    'centos7': 'centos/7',
    'debian8': 'debian/jessie64',
}[cookiecutter.vagrant_box] -%}
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.define "{{ cookiecutter.formula_name }}", primary: true do |host|
        host.vm.box = '{{ vm_box }}'
        host.vm.host_name = '{{ cookiecutter.formula_name }}.salt.example.com'
        host.vm.synced_folder "./", "/srv/salt"
        host.vm.provision "shell", inline: $script
    end
end
